services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: aim-red-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aim-red-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.prod
    container_name: aim-red-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - aim-red-network
    restart: unless-stopped

networks:
  aim-red-network:
    driver: bridge
