version: "3.8"

services:
  backend:
    build: .
    container_name: python-ide-backend
    ports:
      - "8000:8000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "cd packages/backend && python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    networks:
      - ide-network

  frontend:
    build: .
    container_name: python-ide-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
    command: pnpm --filter frontend dev
    depends_on:
      - backend
    networks:
      - ide-network

networks:
  ide-network:
    driver: bridge
