services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: aim-red-backend
    ports:
      - "8000:8000"
    volumes:
      - ./packages/backend:/app
      - ./packages/backend/projects:/app/projects
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aim-red-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: aim-red-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - aim-red-network

networks:
  aim-red-network:
    driver: bridge
