services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile.prod
    container_name: aim-red-backend-prod
    ports:
      - "8000:8000"
    volumes:
      # Only mount the projects directory for persistent storage
      # No source code mounting in production
      - ./packages/backend/projects:/app/projects
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aim-red-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.prod
    container_name: aim-red-frontend-prod
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - aim-red-network
    restart: unless-stopped

networks:
  aim-red-network:
    driver: bridge

